# Generated by Django 3.0.6 on 2020-05-31 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200531_2214'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.AddField(
            model_name='inventory',
            name='item_size',
            field=models.CharField(default='', max_length=3),
        ),
    ]
